// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SmartEyewearStore.Data;

#nullable disable

namespace SmartEyewearStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartEyewearStore.Models.Glasses", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Color")
                    .IsRequired();

                b.Property<string>("FrameShape")
                    .IsRequired();

                b.Property<string>("ImageUrl")
                    .IsRequired();

                b.Property<string>("Name")
                    .IsRequired();

                b.Property<decimal>("Price")
                    .HasPrecision(10, 2);

                b.Property<string>("Style")
                    .IsRequired();

                b.Property<string>("Usage")
                    .IsRequired();

                b.HasKey("Id");

                b.ToTable("Glasses");
            });

            modelBuilder.Entity("SmartEyewearStore.Models.SurveyAnswer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("AgeRange")
                    .IsRequired();

                b.Property<string>("BudgetRange")
                    .IsRequired();


                b.Property<string>("FaceShape")
                    .IsRequired();

                b.Property<string>("Gender")
                    .IsRequired();

                b.Property<string>("PreferredColors")
                    .IsRequired();

                b.Property<string>("Style")
                    .IsRequired();

                b.Property<string>("Usage")
                    .IsRequired();

                b.Property<int>("UserId");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("SurveyAnswers");
            });

            modelBuilder.Entity("SmartEyewearStore.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired();

                b.Property<string>("Password")
                    .IsRequired();

                b.Property<string>("Username")
                    .IsRequired();

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("SmartEyewearStore.Models.SurveyAnswer", b =>
            {
                b.HasOne("SmartEyewearStore.Models.User", "User")
                    .WithMany("Surveys")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("SmartEyewearStore.Models.User", b =>
            {
                b.Navigation("Surveys");
            });
#pragma warning restore 612, 618
        }
    }
}